### ISSUE TITLE
180806DailyWorkLog

### ISSUE THREAD

**Issue by baolianbao** [baolianbao/cygh#2]
**从今天开始，我们组织，每个成员在此更新工作日志。**
工作日志也遵循**成本最少**原则，我推崇 KPTP 法则：
```
K：keep，今天做了哪些工作；

P：problem，遇到了哪些问题；

T：try，计划尝试如何解决这些问题；

P：plan，明天的计划是什么。
```
### Keep: 今日完成了哪些工作
*  9：10 - 10：00 参加「协作规范说明会」
*  10：00 - 11：00 整理公司账目
*  13：00 - 14：00 在线为客户答疑
*  14：00 - 16：00 修复 bug
*  16：00 - 17：00 撰写IPFS + Filecoin 宣传稿
* .....

### Problem: 遇到了什么问题
1. 代码建立审核机制，问题总是暴露在客户那里

### Try： 计划如何解决这些问题
1. 制定代码审核制度，添加到开发流程中，避免问题重复出现

### Plan： 明天的计划是什么
1. 跟客户讨论项目需求
2. 制作项目开发进度表
3. 制定代码审核制度，修改开发流程

每个人按此规则，在此 issue 下回复。

**Comment by sakurahe** [comment]
### Keep: 今日完成了哪些工作 ###
<ol>
<li>参加「协作规范说明会」</li>
<li>创建个人博客</li>
<li>Android Studio学习</li>
<li>nativescript学习</li>
</ol>

### Problem: 遇到了什么问题 ###
<ol>
<li>环境配置经常会遇到报错</li>
</ol>

### Try： 计划如何解决这些问题 ###
<ol>
<li>通过查看资料或者博客，从中寻找解决方法</li>
</ol>

### Plan： 明天的计划是什么 ###
<ol>
<li>使用nativescript搭建一个项目，并试着书写一些简单代码</li>
<li>继续学习nativescript语法</li>
</ol>

**Comment by minitong** [comment]
### Keep: 今日完成了哪些工作 ###
<ul>
<li>参加「协作规范说明会」</li>
<li>配置android studio</li>
<li>创建个人博客</li>
<li>在nativescript playground尝试各种标签，了解nativescript部分语法</li>
</ul>

### Problem: 遇到了什么问题 ###
<ul>
<li>使用android studio配置模拟器（AVD）</li>
</ul>

### Try： 计划如何解决这些问题 ###
<ul>
<li>打算采用和VScode搭配使用其他模拟器，在VScode进行项目开发</li>
</ul>

### Plan： 明天的计划是什么 ###
<ul>
<li>搭建一个项目，研究与模拟器配合使用</li>
<li>研究nativescript语法</li>
</ul>

**Comment by pleasewxh** [comment]
## Keep: 今日完成了哪些工作 ##

**9：10 - 10：00 参加「协作规范说明会」**

**Android Studio初步使用**

## Problem: 遇到了什么问题 ##

**vue init nativescript-vue/vue-cli-template 报错，没有成功启动**

## Try： 计划如何解决这些问题 ##

**根据报错信息逐条查找，重新安装**

## Plan： 明天的计划是什么 ##

**完成一个简单的nativescript-vue项目**

**Comment by PownDs** [comment]
### **Keep: 今日完成了哪些工作**

- 参加「协作规范说明会」
- 撰写「开发协作手册」
- UI界面交互

### **Problem: 遇到了什么问题**

- github不大会玩

### **Try： 计划如何解决这些问题**

- 准备研究下，用github做一个博客

### **Plan： 明天的计划是什么**

- 金数据「客户交接表」
- 招聘Node.js人才

**Comment by sisi123456123** [comment]
### **Keep: 今日完成了哪些工作**

- 参加「协作规范说明会」
- 修改APP钱包功能界面
- 设计APP转账及收款功能界面

### **Problem: 遇到了什么问题**

- github不太熟悉
- APP通讯录功能逻辑梳理

### **Try： 计划如何解决这些问题**

- 一起讨论，采用最少成本的方式解决类似问题

### **Plan： 明天的计划是什么**

- 继续设计APP通讯录功能模块界面
- 整理APP其他界面细节

**Comment by baolianbao** [comment]
##  David Li
### Keep: 今日完成了哪些工作
* 9：10 - 10：00 组织「协作规范说明会」
* 10：00 - 11：00 整理公司5月份账目 
* 13：00 - 14：00 在线为客户答疑
* 14：00 - 16：00 解决笛卡尔官网 bug，无法唤起metamask，profile 页面无法添加地址，以太坊价格不准确。
* 16：00 - 17：00 构思宣传稿（IPFS + Filecoin ）


### Problem: 遇到了什么问题
1. 代码没有建立审核机制，问题总是暴露在客户那里
### Try： 计划如何解决这些问题
1. 开发流程中，增加测试环节，并输出测试报告。
### Plan： 明天的计划是什么
1.  撰写招聘手册
2.  完成公司账目整理
3.  完成 IPFS + FileCoin 宣传稿

**Comment by baolianbao** [comment]
请大家在工作日志首行，加上标题
